# Generated by Django 2.2.28 on 2025-03-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='prep_time',
        ),
    ]
