# Generated by Django 2.2.28 on 2025-03-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20250326_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='value',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='rating',
        ),
    ]
